# Generated by Django 5.2.7 on 2025-10-29 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto',
            name='etiquetas',
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='actualizado',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(max_length=15),
        ),
        migrations.DeleteModel(
            name='Etiqueta',
        ),
        migrations.AddField(
            model_name='contacto',
            name='etiquetas',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
