# Generated by Django 5.2.7 on 2025-10-29 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0002_remove_contacto_etiquetas_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Etiqueta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
            ],
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='telefono',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(max_length=254),
        ),
        migrations.RemoveField(
            model_name='contacto',
            name='etiquetas',
        ),
        migrations.AlterField(
            model_name='contacto',
            name='notas',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contacto',
            name='etiquetas',
            field=models.ManyToManyField(blank=True, to='contactos.etiqueta'),
        ),
    ]
