# Generated by Django 5.2.7 on 2025-10-29 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0003_etiqueta_remove_contacto_telefono_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(default='000000000', max_length=20),
        ),
        migrations.AlterField(
            model_name='contacto',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
