# Generated by Django 5.2.7 on 2025-10-29 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactos', '0004_contacto_telefono_alter_contacto_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contacto',
            name='telefono',
            field=models.CharField(default='', max_length=20),
        ),
    ]
